### PR TITLE
Add pulse flag to build with pulse audio backend on Linux

### PR DESCRIPTION
**Pull request by neosimsim**

### CODE REVIEW

**Review by turion — CHANGES_REQUESTED** [review]
How do I use this flag? Can you add a comment on the correct usage, in particular in a repl?

**Comment by turion** [comment]
Either way, that's very useful.

**Comment by neosimsim** [comment]
I currently see two ways to disable the flag manually. Either by running 

```
cabal configure --constraint 'essence-of-live-coding-tutorial -pulse'
```

or by changing the command in ghicd to

```
cabal repl -f -pulse
```
.

I can comment both in the README if you like.

**Comment by neosimsim** [comment]
> ```
> cabal repl -f -pulse
> ```
Or maybe `—flag`. As a Unix/POSIX fan I usually keep to single letter option but that’s not the general opinion I guess.

**Comment by neosimsim** [comment]
I’d prefer `cabal config` The flag is then persisted in `cabal.project.local` (which should be ignore).
Changing `ghicd` dirties the working git tree.

**Comment by turion** [comment]
Or make the flag default true and add a comment in the readme how to turn it off?

**Comment by neosimsim** [comment]
> Or make the flag default true and add a comment in the readme how to turn it off?

`True` is the default default https://cabal.readthedocs.io/en/3.4/cabal-package.html?highlight=flags#pkg-field-flag-default

**Comment by turion** [comment]
Ah great! Ok then.

**Comment by turion** [comment]
Thanks!

Btw. Someone ran this successfully on a mac and in fact Pulseaudio throws an error there.

**Pull request merged**
